version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  #Certbot renew
  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
      - ../certbot/logs:/var/log/letsencrypt
      - ../certbot/work:/var/www/certbot/work
    entrypoint: /bin/sh -c "while true; do sleep 43200; certbot renew --webroot -w /var/www/certbot --quiet; done"
    networks:
      - app-network
  #Certbot initial for ssl challenge
  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
      - ../certbot/logs:/var/log/letsencrypt
      - ../certbot/work:/var/www/certbot/work
    networks:
      - app-network
  # Serwer Nginx
  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../deploy-repo/prod_My_Resume:/var/www/prod_My_Resume
      - ../deploy-repo/StoryTime:/var/www/StoryTime
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    networks:
      - app-network

volumes:
  dbdata:
    driver: local
  meili_data:
  redis: